name: Extract from Docker

on: push

jobs:
  smoketest:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        version:
          - stable24
          - stable25
          - stable26
          - master
        arch:
          - "386"
          - amd64

    steps:
      - name: Install Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Run
        run: docker build --platform=linux/${{ matrix.arch }} --build-arg NEXTCLOUD_VERSION=${{ matrix.version }} . > "${{ matrix.version }}-${{ matrix.arch }}.log" 2>&1 || true

      - name: Upload log
        uses: actions/upload-artifact@v1
        with:
          name: "${{ matrix.version }}-${{ matrix.arch }}.log"
          path: "${{ matrix.version }}-${{ matrix.arch }}.log"

  deploy:
    runs-on: ubuntu-22.04
    needs: [smoketest]
    if: github.ref_name == 'main'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create folder
      run: mkdir dist

    - name: Download logs
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Create index.html
      run: |
        echo "<!DOCTYPE html><html><body>" > index.html
        echo "<h1>$(date)</h1><ul>" >> index.html
        for i in $(ls dist)
        do
          echo "<li><a href=${i}/${i}>$i</a></li>" >> index.html
        done
        echo "</ul></body></html>" >> index.html
        mv index.html dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: dist
